title: "Hendrik Mayer"    # appears in the browser tab and site header
name: "Hendrik Mayer"

remote_theme: "mmistakes/minimal-mistakes@4.27.3"

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: default
locale: en

author:
  name: "Hendrik Mayer"
  avatar: "/DSC_0834.JPG"   # make sure this file is in your repo root
  bio: "PhD researcher in GNNs & ML."
  location: "Ann Arbor, MI"
