title: "Hendrik Mayer"             # shows in the top-left/site title
name: "Hendrik Mayer"

author:
  name: "Hendrik Mayer"
  avatar: "/IMG_7055.HEIC"   # add this image in step 3
  bio: "PhD researcher in GNNs & ML."
  location: "Ann Arbor, MI"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:htmayer@umich.edu"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/hmayer1"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/hendrik-mayer-0205b8383/"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=29INUCcAAAAJ&hl=en"
